name: CI Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.8.0

      - name: Setup Pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Application
        run: pnpm run build

      - name: Verify Build Output
        run: |
          echo "Build completed. Checking Dist directory..."
          if [ -d "dist" ]; then
            echo "✅ dist directory exists"
            du -sh dist
          else
            echo "dist directory not found!"
            ls -la
            exit 1
          fi

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to Production..."
          npx vercel --token $VERCEL_TOKEN --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
